# 用分割的符号来分割不同的部分表示不同的配置环境   符号为---
# application.yml（文件开头）
#spring: # 在开头写上这段就可以激活了
#  profiles:
#    active: dev

# 虚拟机参数形式
# 如何要在虚拟机上进行配置，则需要打开上面的三个点 打开编辑模式 之后需要修改选项 把虚拟机选项打开 再将-Dspring.profiles.active=test复制进去就行 其中test是配置的名字，也可以是其他的

# 命令行参数形式
# 需要把程序实参打开 再将--spring.profiles.active=pro复制进去就行 其中pro是配置的名字，也可以是其他的

# 也可以通过命令提示符来配置
# 当你将你的程序通过右侧的maven打包成jar包时，
# 你可以在命令提示符中输入java -jar demo-1.0-SNAPSHOT.jar --spring.profiles.active=pro 来激活pro配置

---
server:
  port: 8081
spring:
  config:
    activate:
      on-profile: dev
---
server:
  port: 8084
spring:  # 注意这个新版本的写法 老版本用不了
  config:
    activate:
      on-profile: test
---
server:
  port: 8083
spring:
  config:
    activate:
      on-profile: pro
---