server:
  port: 8082
name: abc   #什么也不做 那么这个name就会注入到Person类中的name属性
# 对象
person:
  name: zhangsan
  age: 20
student: {name: zhangsan,age: 30}
# 数组
address:
  - beijing
  - shanghai
address2: [beijing,shanghai]
#纯量
msg1: "hello\n world" # 双引号会识别
msg2: 'hello\n world' # 单引号不会识别
# 参数引用
personal: lisi
man:
  name: ${personal}  # 引用上面personal的值